apiVersion: v1
kind: Service
metadata:
  name: nginx-ha
spec:
  selector:
    app: nginx-ha
  type: ClusterIP
  ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 80
   - name: https
     protocol: TCP
     port: 443
     targetPort: 443
