services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: my-mongodb
    volumes:
      - /e/Developer/MongodbData:/data/db
    ports:
      - "27017:27017"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: node-dev-env
    working_dir: /usr/src/app
    volumes:
      - /e/Developer:/usr/src/app
      - /c/Users/SilverhandMiles/.vscode/extensions:/home/node/.vscode/extensions
      - /c/Users/SilverhandMiles/AppData/Roaming/Code/User:/home/node/.config/Code/User
      - /c/Users/SilverhandMiles/.gitconfig:/home/node/.gitconfig
      - /c/Users/SilverhandMiles/.ssh:/home/node/.ssh
    network_mode: host

  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    container_name: open-webui
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    ports:
      - "8000:8080"
    volumes:
      - ollama:/root/.ollama
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui:
