services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: my-mongodb
    restart: always
    volumes:
      - /e/Developer/MongodbData:/data/db
    ports:
      - "27017:27017"

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    container_name: node-dev-env
    working_dir: /usr/src/app
    restart: always
    volumes:
      - /e/Developer:/usr/src/app
      - /c/Users/SilverhandMiles/.vscode/extensions:/home/node/.vscode/extensions
      - /c/Users/SilverhandMiles/AppData/Roaming/Code/User:/home/node/.config/Code/User
      - /c/Users/SilverhandMiles/.gitconfig:/home/node/.gitconfig
      - /c/Users/SilverhandMiles/.ssh:/home/node/.ssh
    network_mode: host
