services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: my-mongodb
    restart: always
    volumes:
      - ~/Developer/MongodbData:/data/db
    ports:
      - "27017:27017"

  # nodejs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nodejs
  #   container_name: node-dev-env
  #   working_dir: /usr/src/app
  #   restart: always
  #   volumes:
  #     - ~/Developer:/usr/src/app
  #     - ~/.vscode/extensions:/home/node/.vscode/extensions
  #     - ~/Library/Application\ Support/Code/User/:/home/node/.config/Code/User
  #     - ~/.gitconfig:/home/node/.gitconfig
  #     - ~/.ssh:/home/node/.ssh
  #   network_mode: host

  # clang-gcc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.clang-gcc
  #   container_name: clang-gcc-dev-env
  #   working_dir: /usr/src/app
  #   restart: always
  #   volumes:
  #     - ~/Developer:/usr/src/app
  #     - ~/.vscode/extensions:/home/node/.vscode/extensions
  #     - ~/Library/Application\ Support/Code/User/:/home/node/.config/Code/User
  #     - ~/.gitconfig:/home/node/.gitconfig
  #     - ~/.ssh:/home/node/.ssh
  #   network_mode: host

  # java:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.javacontainer
  #   container_name: java-dev-env
  #   working_dir: /usr/src/app
  #   restart: always
  #   volumes:
  #     - ~/Developer:/usr/src/app
  #     - ~/.vscode/extensions:/home/node/.vscode/extensions
  #     - ~/Library/Application\ Support/Code/User/:/home/node/.config/Code/User
  #     - ~/.gitconfig:/home/node/.gitconfig
  #     - ~/.ssh:/home/node/.ssh
  #   network_mode: host

  # python:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.python
  #   container_name: python-dev-env
  #   working_dir: /usr/src/app
  #   restart: always
  #   volumes:
  #     - ~/Developer:/usr/src/app
  #     - ~/.vscode/extensions:/home/node/.vscode/extensions
  #     - ~/Library/Application\ Support/Code/User/:/home/node/.config/Code/User
  #     - ~/.gitconfig:/home/node/.gitconfig
  #     - ~/.ssh:/home/node/.ssh
  #   network_mode: host

  kali-linux:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali-dev-env
    working_dir: /usr/src/app
    restart: always
    volumes:
      - /e/Developer:/usr/src/app
      - /c/Users/SilverhandMiles/.vscode/extensions:/home/node/.vscode/extensions
      - /c/Users/SilverhandMiles/AppData/Roaming/Code/User:/home/node/.config/Code/User
      - /c/Users/SilverhandMiles/.gitconfig:/home/node/.gitconfig
      - /c/Users/SilverhandMiles/.ssh:/home/node/.ssh
    network_mode: host
