apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-page-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-page-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85

# Note: Ensure that the Deployment 'web-page-deployment' has resource requests defined for CPU to enable HPA functionality.
