apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-page-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-page
  template:
    metadata:
      labels:
        app: web-page
    spec:
      containers:
        - name: therealmileslee.github.io
          image: silverhandlee/therealmileslee-github:latest
          ports:
          - containerPort: 3000
          resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "750m"
          env:
          - name: PORT
            value: "3000"
          readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
