apiVersion: v1
kind: Service
metadata:
  name: web-page-service
spec:
  selector:
    app: web-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - protocol: TCP
      port: 443
      targetPort: 3000
  type: ClusterIP
