apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: silverhandlee/therealmileslee-github:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "500m"       # 0.5 CPU
            memory: "128Mi"
          limits:
            cpu: "4"
            memory: "4Gi"
        # 自动重启挂掉的 Pod
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        # 确保 Pod 准备好接流量
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
