apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
spec:
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: node:trixie
        resources:
          requests:
            cpu: "1"
            memory: "128Mi"
          limits:
            memory: "128Mi"
            cpu: "2"
        ports:
        - containerPort: 3000
