apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-backend
spec:
  replicas: 1                     # 初始副本数
  selector:
    matchLabels:
      app: nodejs-backend
  template:
    metadata:
      labels:
        app: nodejs-backend
    spec:
      containers:
      - name: nodejs-backend
        image: silverhandlee/therealmileslee-github:latest
        resources:
          requests:
            cpu: "0.5"
            memory: "128Mi"
          limits:
            memory: "1Gi"
            cpu: "4"
        ports:
        - containerPort: 3000
