apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logstash-servicelogs-logstash
  namespace: logs
  labels:
    app: logstash
spec:
  serviceName: logstash-headless
  replicas: 6
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.13.4
        imagePullPolicy: IfNotPresent
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "2Gi"
        ports:
        - containerPort: 9600
          name: monitoring
        volumeMounts:
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: pipeline
        configMap:
          name: logstash-pipeline
          items:
          - key: logstash.conf
            path: logstash.conf
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-headless
  namespace: logs
  labels:
    app: logstash
spec:
  clusterIP: None
  selector:
    app: logstash
  ports:
  - name: monitoring
    port: 9600
    targetPort: 9600
    protocol: TCP
