apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline
  namespace: default
  labels:
    app: logstash

data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "external-kafka.default.svc.cluster.local:9094"
        topics => ["pythonTestTopic"]
        group_id => "logstash-consumer-group"
        auto_offset_reset => "latest"
      }
    }
    output {
      stdout { codec => json }
    }
